# Generated by Django 6.0.3 on 2026-04-04 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ProsthesisRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("prosthetist", models.CharField(max_length=255)),
                ("patient", models.CharField(max_length=255)),
                ("procedure", models.CharField(max_length=255)),
                ("send_date", models.DateField(blank=True, null=True)),
                ("receive_date", models.DateField(blank=True, null=True)),
                ("impression_date", models.DateField(blank=True, null=True)),
                (
                    "duration",
                    models.IntegerField(help_text="Duration in days", null=True),
                ),
                ("comments", models.TextField(blank=True)),
                ("appointment_date", models.DateTimeField(blank=True, null=True)),
                ("url", models.URLField(blank=True, max_length=500)),
            ],
        ),
    ]
