# Generated by Django 6.0.4 on 2026-04-08 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_usersrecord'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usersrecord',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='usersrecord',
            name='last_name',
        ),
    ]
