# Generated by Django 6.0.4 on 2026-04-13 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_appointmentrecord'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='appointmentrecord',
            new_name='dashboard_a_date_264dd9_idx',
            old_name='dashboard_a_date_idx',
        ),
    ]
