# Generated by Django 6.0.4 on 2026-04-15 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_calendar_v2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentrecord',
            name='patient_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
