# Generated by Django 6.0.4 on 2026-04-15 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_add_dayrecord'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='dayrecord',
            new_name='dashboard_d_date_6c562d_idx',
            old_name='dashboard_d_date_idx',
        ),
    ]
