# Generated by Django 6.0.4 on 2026-06-29 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_previsionrecord'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EcheanceRecord',
        ),
        migrations.DeleteModel(
            name='PrevisionRecord',
        ),
    ]
